config/routes.rb
Testc::Application.routes.draw do
  resources :accounts do
    collection do
      get 'mypage'
    end
  end

  resources :emps do
    collection do
    end
    member do
        get 'edit_impression'
        put 'update_impression'
    end
    
    resources :emp_selections do
        collection do
            get 'edit_index'
            get 'new_index'
        end
    end
    
  end

  resources :unis do
    collection do
        
    end
    member do
        get 'edit_impression'
        put 'update_impression'
    end 
    
    resources :uni_interviews

    resources :draws
    
    resources :uni_subjects do
        collection do
            get 'edit_index'
            get 'new_index'
        end
    end
    
  end
  
  resources :top, :except => ['show', 'destroy', 'create', 'new', 'edit'] 
  
  resources :login, :except => ['show', 'destroy', 'create', 'new', 'edit'] do
    collection do
        post 'auth'
        get 'logout'
    end
  end
  
  resources :search, :except => ['show', 'destroy', 'create', 'new', 'edit'] do
    collection do
        get 'emp'
        get 'uni'
        post 'result_emp'
        get 'result_emp'
        post 'result_uni'
        get 'result_uni'
    end
  end
  
  root :to => 'top#index'

  match '*a', :to => 'errors#routing', :via => [:get]
end

app/controllers/top_controller.rb
#coding utf-8

#トップに関するコントローラ
class TopController < ApplicationController
    skip_before_filter :check_logined
    
    def index
        respond_to do |format|
            format.html # index.html.erb
        end
    end
      
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/index.html.erb
<% content_for :extend do %>
<div class="hero-unit" align="center" style="background-color:#f5f5f5">
    <h1>試験報告書閲覧システム</h1>
	<br />
    <p>就職試験報告書・進学試験報告書を利用できるシステムです。
      <% if !session[:usr] %>
	<br>利用するには <%= link_to 'ログイン', login_index_path, :style=>"background-color: transparent;" %> してください。</p>
    <% else %>
        <br>
	<%= link_to 'マイページ', mypage_accounts_path, :style=>"background-color: transparent;" %> から報告書を作成・編集できます。</p>
<% end %>
</div>
<% end %>

<div class="row-fluid">
  <div class="span1"></div>
  <div class="span5"><div class="well">
      <div align="center"><h2>就職試験報告書</h2></div>
      <p>就職試験報告書は、先輩方が残してきた就職試験に関する情報です。</p>
	  <br />
      <div align="center">
        <%= link_to emps_path, :class => 'btn' do %>
	<i class="icon-search icon-black"></i> 就職試験報告書を見る »
	<% end %>
      </div>
	  
  </div></div>
  
  <div class="span5"><div class="well">
	  <div align="center"><h2>進学試験報告書</h2></div>
	  <p>進学試験報告書は、先輩方が残してきた進学試験に関する情報です。</p>
	  <br />
	  <div align="center">
            <%= link_to unis_path, :class => 'btn' do %>
	    <i class="icon-search icon-black"></i> 進学試験報告書を見る »
	    <% end %>
	  </div>
  </div></div>
  
  <div class="span1"></div>
</div>