config/routes.rb
Testc::Application.routes.draw do
  resources :accounts do
    collection do
      get 'mypage'
    end
  end

  resources :emps do
    collection do
    end
    member do
        get 'edit_impression'
        put 'update_impression'
    end
    
    resources :emp_selections do
        collection do
            get 'edit_index'
            get 'new_index'
        end
    end
    
  end

  resources :unis do
    collection do
        
    end
    member do
        get 'edit_impression'
        put 'update_impression'
    end 
    
    resources :uni_interviews

    resources :draws
    
    resources :uni_subjects do
        collection do
            get 'edit_index'
            get 'new_index'
        end
    end
    
  end
  
  resources :top, :except => ['show', 'destroy', 'create', 'new', 'edit'] 
  
  resources :login, :except => ['show', 'destroy', 'create', 'new', 'edit'] do
    collection do
        post 'auth'
        get 'logout'
    end
  end
  
  resources :search, :except => ['show', 'destroy', 'create', 'new', 'edit'] do
    collection do
        get 'emp'
        get 'uni'
        post 'result_emp'
        get 'result_emp'
        post 'result_uni'
        get 'result_uni'
    end
  end
  
  root :to => 'top#index'

  match '*a', :to => 'errors#routing', :via => [:get]
end

app/models/uni_subject.rb
#coding: utf-8

class UniSubject < ActiveRecord::Base
  belongs_to :uni

  validates :time,
    :numericality => {
        :allow_blank => true,
        :only_integer => true,
        :greater_than_or_equal_to => 0,
        :less_than => 10000 }

  validates :details,
    :length => { :maximum => 2000, :allow_blank => true}

  validates :subject,
		:presence => { :message => 'は必須です'},
		:length => { :maximum => 30, :minimum => 1, :allow_blank => true}
end

app/controllers/uni_subjects_controller.rb
#coding: utf-8

#進学試験報告書の試験科目を扱うコントローラ
class UniSubjectsController < ApplicationController
  
  #編集を行う前に学籍番号がアカウントと一致するか確認する
  before_filter :check_editer, :only => 'edit_index'
  before_filter :check_editer_subject, :only => 'edit'

  #システムでは使わない
  # GET unis/1/uni_subjects
  # GET unis/1/uni_subjects.json
  def index
    @uni_subjects = UniSubject.all
    @uni = params[:uni_id]
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @uni_subjects }
    end
  end

  #システムでは使わない
  # GET unis/1/uni_subjects/1
  # GET unis/1/uni_subjects/1.json
  def show
    @uni_subject = UniSubject.find(params[:id])
    flash.keep(:edit_subject)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @uni_subject }
    end
  end
    
  #報告書に登録されているいる試験科目一覧
  # GET unis/1/uni_subjects/1
  def new_index
    @uni = Uni.find(params[:uni_id])
    
  end
  
  # 進学試験報告書の試験科目登録フォーム
  # GET unis/1/uni_subjects/new
  # GET unis/1/uni_subjects/new.json
  def new
    @uni_subject = UniSubject.new
    @form_to = uni_uni_subjects_path(params[:uni_id])
    flash.keep(:edit_subject)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @uni_subject }
    end
  end
  
  # 報告書に登録されている試験科目の一覧ページ
  # GET /unis/1/uni_subjects/edit_index
  def edit_index
    @uni = Uni.find(params[:uni_id])
    flash[:edit_subject] = 1
  end

  # 試験科目編集フォーム
  # GET unis/1/uni_subjects/1/edit
  def edit
    @uni_subject = UniSubject.find(params[:id])
    @form_to = uni_uni_subject_path(params[:uni_id],params[:id])
    flash.keep(:edit_subject)
  end

  # 試験科目をデータベースに新規登録
  # POST unis/1/uni_subjects
  # POST unis/1/uni_subjects.json
  def create
    @uni_subject = UniSubject.new(params[:uni_subject])
    @uni_subject.uni = Uni.find(params[:uni_id])
    
    respond_to do |format|
      if @uni_subject.save
            if(!flash[:edit_subject])
                #試験科目一覧に遷移
                format.html { redirect_to new_index_uni_uni_subjects_path(params[:uni_id])}
                format.json { render json: @uni_subject, status: :created, location: @uni_subject }
            else
                format.html { redirect_to edit_index_uni_uni_subjects_path(params[:uni_id])}
            end
      else
        flash.keep(:edit_subject)
        @form_to = uni_uni_subjects_path(params[:uni_id])
        format.html { render action: "new" }
        format.json { render json: @uni_subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # 試験科目の編集内容をデータベースに登録
  # PUT /uni_subjects/1
  # PUT /uni_subjects/1.json
  def update
    @uni_subject = UniSubject.find(params[:id])
    
    respond_to do |format|
      if @uni_subject.update_attributes(params[:uni_subject])
            if(!flash[:edit_subject])
                #試験科目一覧に遷移
                format.html { redirect_to new_index_uni_uni_subjects_path(params[:uni_id])}
                format.json { render json: @uni_subject, status: :created, location: @uni_subject }
            else
                format.html { redirect_to edit_index_uni_uni_subjects_path(params[:uni_id])}
            end
      else
        flash.keep(:edit_subject)
        @form_to = uni_uni_subject_path(params[:uni_id],params[:id])
        format.html { render action: "edit" }
        format.json { render json: @uni_subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE unis/1/uni_subjects/1
  # DELETE unis/1/uni_subjects/1.json
  def destroy
    @uni_subject = UniSubject.find(params[:id])
    flash.keep(:edit_subject)
    
    if(@uni_subject != nil)
        @uni_subject.destroy
    end

    respond_to do |format|
        if(flash[:edit_subject])
            format.html { redirect_to edit_index_uni_uni_subjects_path(params[:uni_id]) }
            format.json { head :no_content }
        else
            format.html { redirect_to new_index_uni_uni_subjects_path(params[:uni_id]) }
        end
    end
  end
  
  private
  def check_editer
    @uni = Uni.find(params[:uni_id])
    if @uni.account.id != session[:usr]
      redirect_to root_path
    end
  end
  
  def check_editer_subject
    @uni_subject = UniSubject.find(params[:id])
    if @uni_subject.uni.account.id != session[:usr]
      redirect_to root_path
    end
  end 
end

app/helpers/uni_subjects_helper.rb
module UniSubjectsHelper
end

app/views/uni_subjects/_form.html.erb
<%= javascript_include_tag "my" %>
<%= form_for(@uni_subject,:url => @form_to,:html => {:class => "form-horizontal"}) do |f| %>
  <% if @uni_subject.errors.any? %>
    <div id="error_explanation">
      <h2>以下の項目を修正してください。</h2>

      <ul>
      <% @uni_subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="control-group">
    <%= f.label :subject, "試験科目",{:class => "control-label"} %>
    <div class="controls">
      <%= f.text_field :subject, {:class => "span2"} %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :time, "試験時間",{:class => "control-label"} %>
    <div class="controls">
      <%= f.number_field :time, :size => "5x5", :step => 5,  :style => "width: 40px"; %>（分）
    </div>
  </div>
  <div class="control-group">
    <%= f.label :details, "詳細",{:class => "control-label"} %>
    <div class="controls">
      <%= f.text_area :details , {:class=>"span4",:rows=>8}%>
    </div>
  </div>
  <div class="form-actions" style="background-color: transparent;">
    <%= f.submit '完了', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/uni_subjects/_index_table.html.erb
<%= link_to '新規科目追加', new_uni_uni_subject_path(@uni), :class=>"btn" %>
<br /><br />
<div class = "table">
    <table>
      <tr>
        <th>科目名</th>
        <th>試験時間</th>
        <th>詳細</th>
        <th></th>
        <th></th>
      </tr>

    <% @uni.uni_subjects.each do |uni_subject| %>
      <tr>
        <td><%= uni_subject.subject %></td>
        <td><%= uni_subject.time %>分</td>
        <td><%= uni_subject.details %></td>
        <td><%= link_to '編集', edit_uni_uni_subject_path(@uni,uni_subject) %></td>
        <td><%= link_to '削除', uni_uni_subject_path(@uni,uni_subject.id), confirm: 'Are you sure?', method: :delete %></td>
      </tr>
    <% end %>
    </table>
</div>

app/views/uni_subjects/edit.html.erb
<h2>試験科目編集</h2>

<%= render 'form' %>

app/views/uni_subjects/edit_index.html.erb
<div class="well">
  <h2>進学報告書 編集 [2/5]</h2>
  <p>この報告書には以下のテスト科目が登録されています。</p>
  <hr>

  <%= render 'index_table' %>

  <hr>
  <%= link_to_function '戻る', 'history.back()', :class => 'btn' %>
  <% if !@uni.uni_interview.blank? %>
  <%= link_to '次へ', edit_uni_uni_interview_path(@uni,@uni.uni_interview), :class=>"btn btn-primary" %>
  <% else %>  
  <%= link_to '次へ', new_uni_uni_interview_path(@uni), :class=>"btn btn-primary" %>
  <% end %>
</div>

app/views/uni_subjects/index.html.erb
<h1>Listing uni_subjects</h1>

<table>
  <tr>
    <th>Uni</th>
    <th>Subject</th>
    <th>Details</th>
    <th>Time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @uni_subjects.each do |uni_subject| %>
  <tr>
    <td><%= uni_subject.uni %></td>
    <td><%= uni_subject.subject %></td>
    <td><%= uni_subject.details %></td>
    <td><%= uni_subject.time %></td>
    <td><%= link_to 'Show', uni_subject %></td>
    <td><%= link_to 'Edit', edit_uni_uni_subject_path(@uni,uni_subject) %></td>
    <td><%= link_to 'Destroy', uni_uni_subject_path(@uni,uni_subject.id), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Uni subject', new_uni_subject_path %>

app/views/uni_subjects/new.html.erb
<div class="well">
  <h2>試験科目登録</h2>
  <p>受けた試験科目の情報を登録します。</p>
  <hr>
  <%= render 'form' %>
</div>

app/views/uni_subjects/new_index.html.erb
<div class="well">
  <h2>進学試験報告書 編集 [2/5]</h2>
  <p>試験科目を登録します。</p>
  <hr>

  <%= render 'index_table' %>

  <hr>
  <%= link_to_function '戻る', 'history.back()', :class => 'btn' %>
  <%= link_to '次へ', new_uni_uni_interview_path(@uni), :class=>"btn btn-primary" %>
</div>

app/views/uni_subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uni:</b>
  <%= @uni_subject.uni %>
</p>

<p>
  <b>Subject:</b>
  <%= @uni_subject.subject %>
</p>

<p>
  <b>Details:</b>
  <%= @uni_subject.details %>
</p>

<p>
  <b>Time:</b>
  <%= @uni_subject.time %>
</p>


<%= link_to 'Edit', edit_uni_subject_path(@uni_subject) %> |
<%= link_to 'Back', uni_subjects_path %>