config/routes.rb
Testc::Application.routes.draw do
  resources :accounts do
    collection do
      get 'mypage'
    end
  end

  resources :emps do
    collection do
    end
    member do
        get 'edit_impression'
        put 'update_impression'
    end
    
    resources :emp_selections do
        collection do
            get 'edit_index'
            get 'new_index'
        end
    end
    
  end

  resources :unis do
    collection do
        
    end
    member do
        get 'edit_impression'
        put 'update_impression'
    end 
    
    resources :uni_interviews

    resources :draws
    
    resources :uni_subjects do
        collection do
            get 'edit_index'
            get 'new_index'
        end
    end
    
  end
  
  resources :top, :except => ['show', 'destroy', 'create', 'new', 'edit'] 
  
  resources :login, :except => ['show', 'destroy', 'create', 'new', 'edit'] do
    collection do
        post 'auth'
        get 'logout'
    end
  end
  
  resources :search, :except => ['show', 'destroy', 'create', 'new', 'edit'] do
    collection do
        get 'emp'
        get 'uni'
        post 'result_emp'
        get 'result_emp'
        post 'result_uni'
        get 'result_uni'
    end
  end
  
  root :to => 'top#index'

  match '*a', :to => 'errors#routing', :via => [:get]
end

app/models/emp_selection.rb
#coding: utf-8

class EmpSelection < ActiveRecord::Base
  belongs_to :emp
  has_one :emp_interview
  has_one :emp_essay
  has_one :emp_test
  
  validates :location,
    :length => { :maximum => 50, :allow_blank => true,
                 :message => 'は文字数は30文字以下にしてください'}
    
end

app/controllers/emp_selections_controller.rb
#coding: utf-8

class EmpSelectionsController < ApplicationController
  #編集を行う前に学籍番号がアカウントと一致するか確認する
  before_filter :check_editer, :only => 'edit'
  
  # 一覧表示、使わない
  # GET /emps/1/emp_selections
  # GET /emps/1/emp_selections.json
  def index
    @emp_selections = EmpSelection.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @emp_selections }
    end
  end
  
  #使わない
  # GET /emps/1/emp_selections/1
  # GET /emps/1/emp_selections/1.json
  def show
    @emp_selection = EmpSelection.find(params[:id])
    flash.keep(:edit_selection)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @emp_selection }
    end
  end
  
  # 報告書に登録されている選考を一覧で表示するページ
  # GET /emps/1/emp_selections/new_index
  def new_index
    @emp = Emp.find(params[:emp_id])
  end
  
  # 選考新規追加入力ページ
  # GET emps/1/emp_selections/new
  # GET emps/1/emp_selections/new.json
  def new
    @emp_selection = EmpSelection.new
    @emp_selection.emp_interview = EmpInterview.new
    @emp_selection.emp_test = EmpTest.new
    @emp_selection.emp_essay = EmpEssay.new
    
    @form_to = emp_emp_selections_path(params[:emp_id])
    flash.keep(:edit_selection)
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @emp_selection }
    end
  end

  # 報告書に登録されている選考を一覧で表示するページ編集用
  # GET emps/1/emp_selections/1/edit_index/
  def edit_index
    @emp = Emp.find(params[:emp_id])
    flash[:edit_selection] = 1
  end
  
  # 選考の編集入力ページ
  # GET emps/1/emp_selections/1/edit
  def edit
    flash.keep(:edit_selection)
    @emp_selection = EmpSelection.find(params[:id])
    @form_to = emp_emp_selection_path(params[:emp_id])
  end
  
  # 選考をデータベースに登録
  # POST /emp_selections
  # POST /emp_selections.json
  def create
    
    @emp_selection = EmpSelection.new(params[:emp_selection])
    @emp_selection.emp_test = EmpTest.new(params[:emp_test])
    @emp_selection.emp_essay = EmpEssay.new(params[:emp_essay])
    @emp_selection.emp_interview = EmpInterview.new(params[:emp_interview])
    
    #関連付け
    @emp_selection.emp = Emp.find(params[:emp_id])
    @emp_selection.emp_test.emp_selection = @emp_selection
    @emp_selection.emp_essay.emp_selection = @emp_selection
    @emp_selection.emp_interview.emp_selection = @emp_selection
    
    @emp_selection.valid?
    if(@emp_selection.errors.any?)
      #エラー処理
      @error_flag = true
    end
    
    @emp_selection.emp_test.valid?
    if(@emp_selection.emp_test.errors.any?)
      #エラー処理
      @error_flag = true
    end
    
    @emp_selection.emp_essay.valid?
    if(@emp_selection.emp_essay.errors.any?)
      #エラー処理
      @error_flag = true
    end

    @emp_selection.emp_interview.valid?
    if(@emp_selection.emp_interview.errors.any?)
      #エラー処理
      @error_flag = true
    end
  
    respond_to do |format|
      if(!@error_flag)
        @emp_selection.save
        if(!flash[:edit_selection])
            # 就職試験報告書の選考一覧ページに遷移
            format.html { redirect_to new_index_emp_emp_selections_path(params[:emp_id]) }
            format.json { render json: @emp_selection, status: :created, location: @emp_selection }
        else
            format.html { redirect_to edit_index_emp_emp_selections_path(params[:emp_id]) }
            format.json { render json: @emp_selection, status: :created, location: @emp_selection }
        end
      else
        @form_to = emp_emp_selections_path(params[:emp_id])
        format.html { render action: "new" }
        format.json { render json: @emp_selection.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # 選考の編集内容をデータベースに登録
  # PUT /emp_selections/1
  # PUT /emp_selections/1.json
  def update
    @emp_selection = EmpSelection.find(params[:id])
    @emp_selection.attributes = params[:emp_selection]
    @emp_selection.emp_interview.attributes = params[:emp_interview]
    @emp_selection.emp_test.attributes = params[:emp_test]
    @emp_selection.emp_essay.attributes = params[:emp_essay]
    
    @emp_selection.emp = Emp.find(params[:emp_id])
    @emp_selection.emp_interview.emp_selection = @emp_selection
    @emp_selection.emp_test.emp_selection = @emp_selection
    @emp_selection.emp_essay.emp_selection = @emp_selection
    
    @emp_selection.valid?
    if(@emp_selection.errors.any?)
      #エラー処理
      @error_flag = true
    end
    
    @emp_selection.emp_test.valid?
    if(@emp_selection.emp_test.errors.any?)
      #エラー処理
      @error_flag = true
    end
    
    @emp_selection.emp_essay.valid?
    if(@emp_selection.emp_essay.errors.any?)
      #エラー処理
      @error_flag = true
    end

    @emp_selection.emp_interview.valid?
    if(@emp_selection.emp_interview.errors.any?)
      #エラー処理
      @error_flag = true
    end
    
    respond_to do |format|
      if !@error_flag 
        @emp_selection.save
        @emp_selection.emp_test.save
        @emp_selection.emp_essay.save
        @emp_selection.emp_interview.save
        
        if(!flash[:edit_selection])
            format.html { redirect_to new_index_emp_emp_selections_path(params[:emp_id]) }
            format.json { render json: @emp_selection, status: :created, location: @emp_selection }
        else
            format.html { redirect_to edit_index_emp_emp_selections_path(params[:emp_id]) }
            format.json { render json: @emp_selection, status: :created, location: @emp_selection }
        end
      else
        @form_to = emp_emp_selection_path(params[:emp_id])
        format.html { render "edit" }
        format.json { render json: @emp_selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emp_selections/1
  # DELETE /emp_selections/1.json
  def destroy
    @emp_selection = EmpSelection.find(params[:id])
    @emp_selection.destroy
    flash.keep(:edit_selection)
    respond_to do |format|
      if(!session[:edit_selection])
        format.html { redirect_to new_index_emp_emp_selections_path(params[:emp_id]) }
      else
        format.html { redirect_to edit_index_emp_emp_selections_path(params[:emp_id]) }
      end
      format.json { head :no_content }
    end
  end
  
  #編集者チェックフィルター
  private
  def check_editer
    @emp_selection = EmpSelection.find(params[:id])
    if @emp_selection.emp.account.id != session[:usr]
      redirect_to root_path
    end
  end
end

app/helpers/emp_selections_helper.rb
module EmpSelectionsHelper
end

app/views/emp_selections/_form.html.erb
<%= javascript_include_tag "my" %>
<%= form_for(@emp_selection, :url => @form_to, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @emp_selection.errors.any? %>
    <div id="error_explanation">
      <h2>選考基本情報に関して、以下の項目を修正してください</h2>

      <ul>
      <% @emp_selection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if @emp_selection.emp_essay.errors.any? %>
    <div id="error_explanation">
      <h2>小論文試験に関して、以下の項目を修正してください</h2>

      <ul>
      <% @emp_selection.emp_essay.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if @emp_selection.emp_interview.errors.any? %>
    <div id="error_explanation">
      <h2>面接試験に関して、項目を修正してください</h2>

      <ul>
      <% @emp_selection.emp_interview.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= field_set_tag '選考基本情報' do %>
    <p>基本情報を入力してください。</p>
    <div class="control-group">
      <%= f.label :glouping, '選考区分', {:class => "control-label"} %>
      <div class="controls">
        <%= f.select( :glouping,{'1次' => 1, '2次' => 2, '3次' => 3, '最終' => 4},{}, :style => "width:70px") %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :location, '選考会場',{:class => "control-label"} %>
      <div class="controls">
        <%= f.text_field :location,{:class => "span3"} %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :start, '選考日',{:class => "control-label"} %>
      <div class="controls">
        <%= f.date_select :start, {:use_month_numbers => true}, :style => "width:70px" %>
         ～ <%= f.date_select :end, {:use_month_numbers => true}, :style => "width:70px" %>
      </div>
    </div>    
    <div class="control-group">
      <%= f.label :result_date, '結果発表日',{:class => "control-label"} %>
      <div class="controls">
        <%= f.date_select :result_date, {:use_month_numbers => true}, :style => "width:70px" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :result, '結果',{:class => "control-label"} %>
      <div class="controls">
        <%= f.select( :result,{'合格' => true, '不合格' => false}, {}, :style => "width:70px") %>
      </div>
    </div>
  <% end %>
  
  <%= field_set_tag '筆記試験' do %>
    <p>筆記試験があった方のみ入力してください。</p>
      <%= fields_for @emp_selection.emp_test do |t| %>
        <div class = "control-group">
            <%= t.label :kind,'試験の種類',{:class => "control-label"} %>
            <div class="controls">
              <%= t.select( :kind,{'会社独自' => 1, 'SPI' => 2, 'その他' =>3},
                      {:include_blank => '選択してください'}, :style => "width:150px") %>
            </div>
        </div>
        <div class = "control-group">
            <%= t.label :details, '詳細（問題の内容等）',{:class => "control-label"} %>
            <div class="controls">
              <%= t.text_area :details,{:class=>"span4",:rows=>8} %>
            </div>
        </div>
      <% end %>
  <% end %>
  
  <%= field_set_tag '小論文試験' do %>
    <p>小論文試験があった方のみ入力してください。</p>
    <%= fields_for @emp_selection.emp_essay do |e|%>
        <div class = "control-group">
            <%= e.label :time, '試験時間',{:class => "control-label"} %>
            <div class="controls">
              <%= e.number_field :time, {:size => 3,:maxlength => 15, :step => 5, :class => "span1"} %>（分）
              <p class="help-block">※半角数字、0以上</p>
            </div>
        </div>
        <div class = "control-group">
            <%= e.label :details, '詳細（題名等）',{:class => "control-label"} %>
            <div class="controls">
              <%= e.text_area :details, {:class=>"span4",:rows=>8} %>
            </div>
        </div>
    <% end %>
  <% end %>
  
  <%= field_set_tag '面接' do %>
    面接試験の内容を登録してください。
    <%= fields_for @emp_selection.emp_interview do |i|%>
        <div class = "control-group">
            <%= i.label :candidates, '面接官',{:class => "control-label"} %>
            <div class="controls">
              <%= i.number_field :candidates, {:size => 3,:maxlength => 5, :step => 1, :class => "span1"} %>（人）
              <p class="help-block">※半角数字、0以上</p>
            </div>
        </div>
        <div class = "control-group">
            <%= i.label :examiners, '（集団面接のみ）同時に面接を受けた人数',{:class => "control-label"} %>
            <div class="controls">
              <%= i.number_field :examiners, {:size => 3,:maxlength => 5, :step => 1, :class => "span1"} %>（人）
              <p class="help-block">※半角数字、0以上</p>
            </div>
        </div>
        <div class = "control-group">
            <%= i.label :time, '試験時間',{:class => "control-label"} %>
            <div class="controls">
              <%= i.number_field :time, {:size => 3,:maxlength => 15, :step => 5, :class => "span1"} %>（分）
              <p class="help-block">※半角数字、0以上</p>
            </div>
        </div>
        <div class = "control-group">
            <%= i.label :details, '面接の詳細な内容',{:class => "control-label"} %>
            <div class="controls">
              <%= i.text_area :details,{:class=>"span4",:rows=>8} %>
            </div>
        </div>
    <% end %>
  <% end %>
  
  <div class="form-actions" style="background-color:transparent;">
	<%= link_to_function '戻る', 'history.back()', :class => 'btn' %>
    <%= f.submit '次へ', :class=>"btn btn-primary" %>
  </div>
  
<% end %>

app/views/emp_selections/_index_table.html.erb
<%= link_to '選考追加', new_emp_emp_selection_path(@emp),:class => "btn" %>
<br /><br />
<div class=table>
<table>
  <tr>
    <th>選考</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @emp.emp_selections.each do |emp_selection| %>
  <tr>
    <td>
        <% if emp_selection.glouping == 4 %>
            最終
        <% else %>
            <%= emp_selection.glouping %>次
        <% end %>
    </td>
    <td><%= link_to '編集', edit_emp_emp_selection_path(@emp,emp_selection), :style=>"background-color:transparent;" %></td>
    <td><%= link_to '削除', emp_emp_selection_path(@emp,emp_selection), confirm: 'Are you sure?', method: :delete, :style=>"background-color:transparent;" %></td>
  </tr>
<% end %>
</table>
</div>

app/views/emp_selections/edit.html.erb
<h2>選考の編集</h2>

<%= render 'form' %>

app/views/emp_selections/edit_index.html.erb
<h2>就職報告書編集 2/3</h2>
選考についての情報を登録してください。
<br /><br />

<%= render 'index_table' %>

<br />
<br />

<%= link_to '次へ', edit_impression_emp_path(@emp),:class => "btn" %>

app/views/emp_selections/index.html.erb
<h1>Listing emp_selections</h1>

<table>
  <tr>
    <th>Emp</th>
    <th>Glouping</th>
    <th>Start</th>
    <th>End</th>
    <th>Location</th>
    <th>Result date</th>
    <th>Result</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @emp_selections.each do |emp_selection| %>
  <tr>
    <td><%= emp_selection.emp.id %></td>
    <td><%= emp_selection.glouping %></td>
    <td><%= emp_selection.start %></td>
    <td><%= emp_selection.end %></td>
    <td><%= emp_selection.location %></td>
    <td><%= emp_selection.result_date %></td>
    <td><%= emp_selection.result %></td>
    <td><%= link_to 'Show', emp_selection %></td>
    <td><%= link_to 'Edit', edit_emp_selection_path(emp_selection) %></td>
    <td><%= link_to 'Destroy', emp_selection, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Emp selection', new_emp_selection_path %>

app/views/emp_selections/new.html.erb
<div class="well">
<h2>選考登録</h2>

<%= render 'form' %>
</div>

app/views/emp_selections/new_index.html.erb
<div class="well">
  <h2>就職試験報告書 編集 [2/3]</h2>
  <p>次の選考に進んだ場合、その情報も登録してください。</p>

  <%= render 'index_table' %>

  <hr>
  <%= link_to_function '戻る', 'history.back()', :class => 'btn' %>
  <%= link_to '次へ', edit_impression_emp_path(@emp),:class => "btn btn-primary" %>
</div>

app/views/emp_selections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Emp:</b>
  <%= @emp_selection.emp %>
</p>

<p>
  <b>Glouping:</b>
  <%= @emp_selection.glouping %>
</p>

<p>
  <b>Start:</b>
  <%= @emp_selection.start %>
</p>

<p>
  <b>End:</b>
  <%= @emp_selection.end %>
</p>

<p>
  <b>Location:</b>
  <%= @emp_selection.location %>
</p>

<p>
  <b>Result date:</b>
  <%= @emp_selection.result_date %>
</p>

<p>
  <b>Result:</b>
  <%= @emp_selection.result %>
</p>


<%= link_to 'Edit', edit_emp_selection_path(@emp_selection) %> |
<%= link_to 'Back', emp_selections_path %>