config/routes.rb
Testc::Application.routes.draw do
  resources :accounts do
    collection do
      get 'mypage'
    end
  end

  resources :emps do
    collection do
    end
    member do
        get 'edit_impression'
        put 'update_impression'
    end
    
    resources :emp_selections do
        collection do
            get 'edit_index'
            get 'new_index'
        end
    end
    
  end

  resources :unis do
    collection do
        
    end
    member do
        get 'edit_impression'
        put 'update_impression'
    end 
    
    resources :uni_interviews

    resources :draws
    
    resources :uni_subjects do
        collection do
            get 'edit_index'
            get 'new_index'
        end
    end
    
  end
  
  resources :top, :except => ['show', 'destroy', 'create', 'new', 'edit'] 
  
  resources :login, :except => ['show', 'destroy', 'create', 'new', 'edit'] do
    collection do
        post 'auth'
        get 'logout'
    end
  end
  
  resources :search, :except => ['show', 'destroy', 'create', 'new', 'edit'] do
    collection do
        get 'emp'
        get 'uni'
        post 'result_emp'
        get 'result_emp'
        post 'result_uni'
        get 'result_uni'
    end
  end
  
  root :to => 'top#index'

  match '*a', :to => 'errors#routing', :via => [:get]
end

app/models/account.rb
#coding: utf-8

class Account < ActiveRecord::Base

	has_many :unis
	has_many :emps
	
	validates :student_id,
		:presence => { :message => 'は必須です'},
		:uniqueness => {:allow_blank => true,
                    :message => 'はすでに登録されている学籍番号です'},
		:length => { :is => 5, :allow_blank => true,
                    :message => 'は半角数字5文字で入力してください' },
		:format => { :with => /^[0-9]{5}$/, :allow_blank => true,
                    :message => 'は半角数字5文字で入力してください'}
	validates :name,
		:presence => { :message => 'は必須です' },
		:length => { :maximum => 30, :minimum => 1, :allow_blank => true,
                :message => 'は文字数は30文字以下にしてください'}
	validates :major,
		:presence => true,
		:numericality => { :allow_blank => true,
            :only_integer => true, :greater_than => 0, :less_than => 6}
	validates :password,
                :presence => true,
                :confirmation => {:message => '入力が一致しません'}

  def self.authenticate(student,password)
    where(:student_id => student,
        :password => Digest::SHA1.hexdigest(password)).first
  end
end

app/controllers/accounts_controller.rb
#coding: utf-8

class AccountsController < ApplicationController
  #ログインチェックフィルターを一部でスキップする
  skip_filter :check_logined, :only => ['new','show','create']
  #編集を行う前に学籍番号がアカウントと一致するか確認する
  before_filter :check_editer, :only => 'edit'

  #マイページの表示
  # GET /accounts/mypage
  def mypage
    @account = Account.find(session[:usr])
    @emps = Emp.where("account_id == ?", session[:usr]).page.order("created_at DESC").page(params[:page]).per(20)
    @unis = Uni.where("account_id == ?", session[:usr]).page.order("created_at DESC").page(params[:page]).per(20)
  end

  #アカウント一覧
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])
    #パスワードはハッシュ化して登録
    @account.password = Digest::SHA1.hexdigest(@account.password)
    @account.password_confirmation = Digest::SHA1.hexdigest(@account.password_confirmation)
    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'アカウントが正常に作成されました。' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])
    @account.attributes = params[:account]
    @account.password = Digest::SHA1.hexdigest(@account.password)
    @account.password_confirmation = Digest::SHA1.hexdigest(@account.password_confirmation)
    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'アカウントが正常に更新されました。' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
  
  private
  def check_editer
    @account = Account.find(params[:id])
    if @account.id != session[:usr]
      redirect_to root_path
    end
  end
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account,:html => {:class => "form-horizontal"}) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2> 以下の項目を修正してください</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :学籍番号,{:class => "control-label"} %>
    <div class="controls">
        <%= f.text_field :student_id, :style=>"width:40px" %>
        <p class="help-block">※必須 5文字の半角数字</p>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :名前,{:class => "control-label"} %>
    <div class="controls">
        <%= f.text_field :name, :style=>"width:100px" %>        
        <p class="help-block">※必須</p>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :学科,{:class => "control-label"} %>
    <div class="controls">
      <%= f.select( :major, 
            {'M' => 1, 'E' => 2, 'S' => 3, 'J' => 4, 'C' => 5},
            {},:style=>"width:50px")%>
      <p class="help-block">※必須</p>
    </div>
  </div>
  
  <div class="control-group">
		<%= f.label :パスワード,{:class => "control-label"} %>
    <div class="controls">
      <%= f.password_field :password, :style=>"width:100px" %>
      <p class="help-block">※必須</p>
    </div>
  </div>
  
  <div class="control-group">
		<%= f.label :パスワード（確認用）,{:class => "control-label"} %>
    <div class="controls">
      <%= f.password_field :password_confirmation, :style=>"width:100px"%>
      <p class="help-block">※必須</p>
    </div>
  </div>
  
  <div class="form-actions" style="background-color: transparent;">
    <%= f.submit '登録', {:class => "btn btn-primary"} %>
  </div>
  
<% end %>

app/views/accounts/_form_edit.html.erb
<%= form_for(@account,:html => {:class => "form-horizontal"}) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2> 以下の項目を修正してください</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :学籍番号,{:class => "control-label"} %>
    <div class="controls">
        <%= f.text_field :student_id, :style=>"width:40px", :class=>"input disabled" %>
        <p class="help-block">※必須 5文字の半角数字</p>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :名前,{:class => "control-label"} %>
    <div class="controls">
        <%= f.text_field :name, :style=>"width:100px" %>        
        <p class="help-block">※必須</p>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :学科,{:class => "control-label"} %>
    <div class="controls">
      <%= f.select( :major, 
            {'M' => 1, 'E' => 2, 'S' => 3, 'J' => 4, 'C' => 5},
            {},:style=>"width:50px")%>
      <p class="help-block">※必須</p>
    </div>
  </div>
  
  <div class="control-group">
		<%= f.label :パスワード,{:class => "control-label"} %>
    <div class="controls">
      <%= f.password_field :password, :style=>"width:100px" %>
      <p class="help-block">※必須</p>
    </div>
  </div>
  
  <div class="control-group">
		<%= f.label :パスワード（確認用）,{:class => "control-label"} %>
    <div class="controls">
      <%= f.password_field :password_confirmation, :style=>"width:100px"%>
      <p class="help-block">※必須</p>
    </div>
  </div>
  
  <div class="form-actions" style="background-color: transparent;">
    <%= f.submit '登録', {:class => "btn btn-primary"} %>
  </div>
  
<% end %>

app/views/accounts/_index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th>Student</th>
    <th>Name</th>
    <th>Major</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.student_id %></td>
    <td><%= account.name %></td>
    <td><%= account.major %></td>
    <td><%= account.password %></td>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>

app/views/accounts/edit.html.erb
<%= javascript_include_tag "error" %>

<div class="row-fluid">
  <div class="span2"></div>
	<div class="span8">
	  <div class="well">
		<h2>アカウント情報編集</h2>
		<hr>
		<%= render 'form_edit' %>
	  </div>
	</div>  
	<div class="span2"></div>
</div>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th>Student</th>
    <th>Name</th>
    <th>Major</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.student_id %></td>
    <td><%= account.name %></td>
    <td><%= account.major %></td>
    <td><%= account.password %></td>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>

app/views/accounts/mypage.html.erb
<div class="well">
<div class="row-fluid">
  <div class="span6">
	   <h2><%= @account.name %> さん (<%= @account.student_id %>) のマイページ</h2>
  </div>
  <div class="span6" align="right">
	<br />
        <%= link_to edit_account_path(@account), :class => 'btn' do %>
	<i class="icon-pencil icon-black"></i> アカウント情報編集 »
	<% end %>
  </div>
</div>
<hr>

<div class="row-fluid">
  <div class="span6">
	<h3>作成した就職試験報告書</h3>
  </div>
  <div class="span6" align="right">
	<br />
        <%= link_to new_emp_path, :class => 'btn' do %>
	<i class="icon-pencil icon-black"></i> 就職試験報告書の新規作成 »
	<% end %>
  </div>
</div>

<% if @emps.blank? %>
  まだ作成していません。
<% else %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>報告者</th>
        <th>会社名</th>
        <th>選考</th>
        <th>作成日</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
  <% @emps.each do |emp| %>
    <tbody>
    <tr>
      <td><%= emp.account.student_id %></td>
      <td><%= link_to emp.name, emp, :style=>"background-color: transparent;" %></td>
      <td><% emp.emp_selections.each do |selection| %>
          <%= selection.glouping %>次
      <% end %></td>
      <td><%= emp.created_at.strftime("%Y年%m月%d日") %>
      <% if emp.account.id == session[:usr] %>
          <td style="text-align:center;", width="35"><%= link_to '編集', edit_emp_path(emp), :style=>"background-color: transparent;" %></td>
          <td style="text-align:center;", width="35"><%= link_to '消去', emp, method: :delete, :style=>"background-color: transparent;", :confirm => "本当に削除しますか？"  %></td>
      <% end %>
    </tr>
    </tbody>
  <% end %>
  </table>

  <div style="text-align:center">
    <%= paginate @emps %>
  </div>
<% end %>

<hr>

<div class="row-fluid">
  <div class="span6">
	<h3>作成した進学試験報告書</h3>
  </div>
  <div class="span6" align="right">
	<br />
        <%= link_to new_uni_path, :class => 'btn' do %>
	<i class="icon-pencil icon-black"></i> 進学試験報告書の新規作成 »
	<% end %>
  </div>
</div>

<% if @unis.blank? %>
  まだ作成していません。
<% else %>
  <table class="table table-bordered">
    <tr>
      <th>報告者</th>
      <th>大学名</th>
      <th>学科</th>
      <th>作成日</th>
      <th></th>
      <th></th>
    </tr>

  <% @unis.each do |uni| %>
    <tr>
      <td><%= uni.account.student_id %></td>
      <td><%= link_to uni.name, uni, :style=>"background-color: transparent;" %></td>
      <td><%= uni.major %></td>
      <td><%= uni.created_at.strftime("%Y年%m月%d日") %>
      <% if uni.account.id == session[:usr] %>
          <td style="text-align:center;", width="35"><%= link_to '編集', edit_uni_path(uni), :style=>"background-color: transparent;" %></td>
          <td style="text-align:center;", width="35"><%= link_to '削除', uni, method: :delete, :style=>"background-color: transparent;", :confirm=>'本当に削除しますか？' %></td>
      <% end %>
    </tr>
  <% end %>
  </table>
  <div style="text-align:center">
	<%= paginate @unis %>
  </div>
<% end %>
</div>

app/views/accounts/new.html.erb
<%= javascript_include_tag "error" %>

<div class="row-fluid">
  <div class="span2"></div>
  <div class="span8">
	<div class="well">
	  <h2>新規アカウント作成</h2>
	  <hr>
	  <%= render 'form' %>
	</div>
  </div>
  <div class="span2"></div>
</div>


app/views/accounts/show.html.erb
<div class="row-fluid">
  <div class="span3"></div>
  <div class="span6">
	<div class="well">
	  <p id="notice"><%= notice %></p>
	  <h2>アカウント情報</h2>
	  <hr>
	  <table class="table table-bordered">
		<tr>
		  <th>アカウントID</th>
		  <th>名前</th>
		  <th>学科</th>
		</tr>

		<tr>
		  <th><%= @account.id %></th>
		  <th><%= @account.name %></th>
		  <th>
			<% if @account.major == 1 %>
			M科
			<% elsif @account.major == 2 %>
			E科
			<% elsif @account.major == 3 %>
			S科
			<% elsif @account.major == 4 %>
			J科
			<% elsif @account.major == 5 %>
			C科
			<% end %>
		  </th>
	  </table>
	  <hr>
	  <% if !session[:usr] %>
	    <%= link_to '編集 »', edit_account_path(@account), :class=>"btn"%> 
	    <%= link_to 'ログイン »', '/login', :class=>"btn btn-primary" ,:type=>"submit" %>
	  <% else %>
	    <%= link_to 'マイページ »', mypage_accounts_path, :class=>"btn"%> 
	  <% end %>
	</div>
  </div>
  <div class="span3"></div>
</div>